# Generated by Django 3.0.6 on 2020-06-03 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='author',
            new_name='user',
        ),
    ]
